config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  namespace :owner, only: [] do
    resources :chapters, except: [:show] do
      resources :sections, except: [] do
      end
    end
  end

  resources :chapters, only: [] do
    resources :sections, only: %i[index show] do
    end
  end
end

app/models/section.rb
# frozen_string_literal: true

class Section < ApplicationRecord
  has_one_attached :media, dependent: :destroy

  # validates
  validates :title,
            presence: true,
            length: {
              maximum: 30
            }

  # relationship
  belongs_to :chapter

  def publishd_state
    [
      %w[
        草稿 draft
      ],
      %w[
        發布 publish
      ]
    ]
  end
end

app/controllers/owner/chapters_controller.rb
# frozen_string_literal: true

module Owner
  class ChaptersController < ApplicationController
    before_action :find_chapter, only: %i[edit update destroy]

    def index
      @chapters = Chapter.all
    end

    def new
      @chapter = Chapter.new
    end

    def create
      @chapter = current_user.chapters.new(chapter_params)

      if @chapter.save
        redirect_to owner_chapters_path, notice: '新增成功'
      else
        flash.now[:alert] = '請輸入正確資訊'
        render :new
      end
    end

    def edit; end

    def update
      if @chapter.update(chapter_params)
        redirect_to owner_chapters_path, notice: '更新成功'
      else
        flash.now[:alter] = '請輸入正確資訊'
        render :edit
      end
    end

    def destroy
      @chapter.sections.delete_all && @chapter.destroy
      redirect_to owner_chapters_path, notice: '刪除chapter!!'
    end

    private

    def chapter_params
      params.require(:chapter).permit(:title)
    end

    def find_chapter
      @chapter = Chapter.find(params[:id])
    end
  end
end

app/controllers/owner/sections_controller.rb
# frozen_string_literal: true

module Owner
  class SectionsController < ApplicationController
    before_action :find_section, only: %i[show edit update destroy]

    def index; end

    def new
      @section = Section.new
    end

    def create
      chapter = Chapter.find(params[:chapter_id])
      @section = chapter.sections.new(section_params)

      if @section.save
        redirect_to owner_chapters_path, notice: '新增成功'
      else
        flash.now[:alert] = '請輸入正確資訊'
        render :new
      end
    end

    def edit; end

    def update
      if @section.update(section_params)
        redirect_to owner_chapters_path, notice: '更新成功'
      else
        flash.now[:alert] = '請輸入正確資訊'
        render :edit
      end
    end

    def destroy
      if @section.media.attached?
        @section.media.purge_later
        @section.destroy
        redirect_to owner_chapters_path, notice: '刪除成功（有影片）'
      else
        @section.destroy
        redirect_to owner_chapters_path, notice: '刪除成功'
      end
    end

    def show; end

    private

    def section_params
      params.require(:section).permit(:title, :content, :published, :finished, :media)
    end

    def find_section
      chapter = Chapter.find(params[:chapter_id])
      @section = chapter.sections.find(params[:id])
    end
  end
end

app/controllers/sections_controller.rb
# frozen_string_literal: true

class SectionsController < ApplicationController
end

app/views/owner/sections/edit.html.erb
<h1>編輯Section</h1>

<%= form_with model: @section, url: owner_chapter_section_path(@section.chapter_id, @section.id) do |form| %>

  <div class="field">
    <%= form.label :title, "標題" %>
    <%= form.text_field :title %>
  </div>
  
  <div class="field">
    <%= form.label :media, "上傳影片" %>
    <%= form.file_field :media %>
  </div> 
  
  <div class="field">
    <%= form.label :content, "課程內文" %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.select :published, @section.publishd_state %>
  </div>  

  <%= form.submit "送出" %>
<% end %>

app/views/owner/sections/new.html.erb
<h1>新增Section</h1>

<%= form_with model: @section, url: owner_chapter_sections_path, method: "post" do |form| %>
  <div class="field">
    <%= form.label :title, "標題" %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :media, "上傳影片" %>
    <%= form.file_field :media %>
  </div>

  <div class="field">
    <%= form.label :content, "課程內文" %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.select :published, @section.publishd_state %>
  </div>

  <%= form.submit "送出" %>
<% end %>

app/views/owner/sections/show.html.erb
<%= @section.title %>
<%= @section.content %>
<%= video_tag url_for(@section.media), size: "400x400",  controls: true if @section.media.attached? %>