config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  namespace :owner, only: [] do
    resources :chapters, except: [:show] do
      resources :sections, except: [] do
      end
    end
  end

  resources :chapters, only: [] do
    resources :sections, only: %i[index show] do
    end
  end
end

app/views/shared/_chaopter_list.html.erb
<ul class="chapter-list">
  <%= render partial: "/shared/chapter", collection: @chapters %>
</ul>

app/views/shared/_chapters.html.erb
<li>
  <li><%= chapter.title %></li>
  <ul>
      <% chapter.sections.each do |section| %>
        <li><%= link_to section.title, edit_owner_chapter_section_path(section.chapter_id, section.id) %></li>
      <% end %>
    </ul>
</li>

app/views/shared/_flash.html.erb
<div>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
</div>

app/views/shared/_nav.html.erb
<nav class="flex items-center justify-between px-4" >

  <%= link_to root_path, class: "py-2 bg-green-500" do %>
    <h1 class="text-4xl ">Teacherfly</h1>
  <% end %>
  
  <div class="">  
    <% if current_user %>
      <%= link_to('登出', destroy_user_session_path, :method => :delete) %> |
      <%= link_to('修改密碼', edit_registration_path(:user)) %>
    <% else %>
      <%= link_to('註冊', new_registration_path(:user)) %> |
      <%= link_to('登入', new_session_path(:user)) %>
    <% end %>
  </div>

</nav>