config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  namespace :owner, only: [] do
    resources :chapters, except: [:show] do
      resources :sections, except: [] do
      end
    end
  end

  resources :chapters, only: [] do
    resources :sections, only: %i[index show] do
    end
  end
end

app/models/chapter.rb
# frozen_string_literal: true

class Chapter < ApplicationRecord
  # validates
  validates :title,
            presence: true,
            length: {
              maximum: 20
            }

  # relationship
  belongs_to :user
  has_many :sections
end

app/controllers/chapters_controller.rb
# frozen_string_literal: true

class ChaptersController < ApplicationController
end

app/controllers/owner/chapters_controller.rb
# frozen_string_literal: true

module Owner
  class ChaptersController < ApplicationController
    before_action :find_chapter, only: %i[edit update destroy]

    def index
      @chapters = Chapter.all
    end

    def new
      @chapter = Chapter.new
    end

    def create
      @chapter = current_user.chapters.new(chapter_params)

      if @chapter.save
        redirect_to owner_chapters_path, notice: '新增成功'
      else
        flash.now[:alert] = '請輸入正確資訊'
        render :new
      end
    end

    def edit; end

    def update
      if @chapter.update(chapter_params)
        redirect_to owner_chapters_path, notice: '更新成功'
      else
        flash.now[:alter] = '請輸入正確資訊'
        render :edit
      end
    end

    def destroy
      @chapter.sections.delete_all && @chapter.destroy
      redirect_to owner_chapters_path, notice: '刪除chapter!!'
    end

    private

    def chapter_params
      params.require(:chapter).permit(:title)
    end

    def find_chapter
      @chapter = Chapter.find(params[:id])
    end
  end
end

app/controllers/owner/sections_controller.rb
# frozen_string_literal: true

module Owner
  class SectionsController < ApplicationController
    before_action :find_section, only: %i[show edit update destroy]

    def index; end

    def new
      @section = Section.new
    end

    def create
      chapter = Chapter.find(params[:chapter_id])
      @section = chapter.sections.new(section_params)

      if @section.save
        redirect_to owner_chapters_path, notice: '新增成功'
      else
        flash.now[:alert] = '請輸入正確資訊'
        render :new
      end
    end

    def edit; end

    def update
      if @section.update(section_params)
        redirect_to owner_chapters_path, notice: '更新成功'
      else
        flash.now[:alert] = '請輸入正確資訊'
        render :edit
      end
    end

    def destroy
      if @section.media.attached?
        @section.media.purge_later
        @section.destroy
        redirect_to owner_chapters_path, notice: '刪除成功（有影片）'
      else
        @section.destroy
        redirect_to owner_chapters_path, notice: '刪除成功'
      end
    end

    def show; end

    private

    def section_params
      params.require(:section).permit(:title, :content, :published, :finished, :media)
    end

    def find_section
      chapter = Chapter.find(params[:chapter_id])
      @section = chapter.sections.find(params[:id])
    end
  end
end

app/views/owner/chapters/edit.html.erb
<h1>編輯Chapter</h1>

<%= render "shared/flash" %>

<%= form_with model: @chapter, url: owner_chapter_path do |form| %>
  <div class="field">
    <%= form.label :title, "標題" %>
    <%= form.text_field :title %>
  </div>
  
  <%= form.submit %>
<% end %>

app/views/owner/chapters/index.html.erb
<h1>後台：Chapter列表</h1>

<%= render "shared/flash" %>

<ul>
  <% @chapters.each do |chapter|%>
    <li>章節：<%= chapter.title %> | 
      <%= link_to "X", owner_chapter_path(chapter), method: "delete" %> | 
      <%= link_to "編輯", edit_owner_chapter_path(chapter) %> 
    </li>
    <ul>
      <% chapter.sections.each do |section| %>
        <li>
          <%= link_to section.title, owner_chapter_section_path(section.chapter_id, section.id) %> | 
          <%= link_to "X", owner_chapter_section_path(section.chapter_id, section), method: "delete" %>
        </li>
        <li>
          <%= link_to "編輯", edit_owner_chapter_section_path(section.chapter_id, section.id) %>
        </li>
      <% end %>
    </ul>
    <%= link_to "新增Section", new_owner_chapter_section_path(chapter.id) %>
  <% end %>
</ul>

<%= link_to "新增Chapter", new_owner_chapter_path %>

app/views/owner/chapters/new.html.erb
<h1>新增Chapter</h1>

<%= render "shared/flash" %>

<%= form_with model: @chapter, url: owner_chapters_path do |form| %>
  <div class="field">
    <%= form.label :title, "標題" %>
    <%= form.text_field :title %>
  </div>
  
  <%= form.submit "送出" %>
<% end %>